accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = "accounts"

urlpatterns = [
    
    path("logout/", views.logout_view, name="logout"),
    path("signup/", views.signup_view, name="signup"),
    path("login/", views.login_view, name="login"),
    
    # reset password django.contrib.auth
    path(
        "password_reset/",
        views.CustomPasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.CustomPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.CustomPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestEntriesFeed

app_name = 'blog'

urlpatterns = [
    path('', views.blog_list_view, name='list_view'),
    path('category/<str:cat_name>/', views.blog_list_view, name='category'),
    path('tag/<str:tag_name>/', views.blog_list_view, name='tag'),
    path('search/', views.blog_search_view, name='search'),
    path('<int:pk>/', views.blog_detail_view, name='detail_view'),
    path("rss/feed/", LatestEntriesFeed()),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap

import debug_toolbar

from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap

sitemaps = {
    "static": StaticViewSitemap,
    "blog": BlogSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),

    # app urls
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),


    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path('robots.txt', include('robots.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
    path('tinymce/', include('tinymce.urls')),
    path('captcha/', include('captcha.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _


class CustomUser(AbstractUser):
    email = models.EmailField(_("email address"), unique=True)

    def __str__(self):
        return self.username

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
from django import forms

from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ("email", "username")

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ("email", "username")

class CustomAuthenticationForm(AuthenticationForm):
    remember_me = forms.BooleanField(required=False)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login , logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView
from django.urls import reverse_lazy



from .forms import CustomUserCreationForm, CustomAuthenticationForm


class CustomPasswordResetView(PasswordResetView):
    success_url = reverse_lazy('accounts:password_reset_done')


class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    success_url = reverse_lazy('accounts:password_reset_complete')
    
    
def login_view(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = CustomAuthenticationForm(request=request, data=request.POST)
            if form.is_valid():
                user_input = form.cleaned_data.get('username')
                password = form.cleaned_data.get('password')
                remember_me = form.cleaned_data.get('remember_me')
                user = authenticate(request, username=user_input, password=password)
                if user is not None:
                    login(request, user)
                    if remember_me: 
                    # This if statement can change, 
                    # but the purpose is checking remember me checkbox is checked or not.
                        request.session.set_expiry(604800) # Here we extend session.
                    else:
                        # This part of code means, close session when browser is closed.
                        request.session.set_expiry(0)
                    messages.success(request, "Login successful")
                    return redirect('/')
            else:
                messages.error(request, "Invalid username or password")
        form = CustomAuthenticationForm()
        context = {'form': form}    
        return render(request, 'accounts/login.html', context)
    else: 
        return redirect('/')
        
            
        
@login_required
def logout_view(request):
    logout(request)
    return redirect('/')
        

def signup_view(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = CustomUserCreationForm(request.POST)
            if form.is_valid():
                form.save()
                messages.success(request, "you are Signed Up!")
                return redirect('accounts:login')

        form = CustomUserCreationForm()
        context = {'form': form}
        return render(request, 'accounts/signup.html', context)
    else:
        return redirect("/")

templates/accounts/login.html
{% extends 'base_accounts.html' %}


{% block content %}

<div class="login-wrap p-4 p-md-5">
  <div class="d-flex">
    <div class="w-100">
      <h3 class="mb-4">Sign In</h3>
    </div>
  </div>
  <form
    action="{% url 'accounts:login' %}"
    class="signin-form"
    method="post"
  >
    {% csrf_token %}
    {{ block.super }}
    <div class="form-group mt-3">
    <input
      type="text" 
      name="username"
      class="form-control"
      required
    />
    <label class="form-control-placeholder" for="username"
      >Username or email</label
    >
  </div>
  <div class="form-group">
      <input
        id="password-field"
        type="password"
        class="form-control"
        name="password"
        required
      />
      <label class="form-control-placeholder" for="password"
        >Password</label
      >
      <span
        toggle="#password-field"
        class="fa fa-fw fa-eye field-icon toggle-password"
      ></span>
    </div>
    <div class="form-group">
      <button
        type="submit"
        class="form-control btn btn-primary rounded submit px-3"
      >
        Sign In
      </button>
    </div>
    <div class="form-group d-md-flex">
      <div class="w-50 text-left">
        <label class="checkbox-wrap checkbox-primary mb-0"
          >Remember Me
          <input type="checkbox" name="remember_me" checked />
          <span class="checkmark"></span>
        </label>
      </div>
      <div class="w-50 text-md-right">
        <a href="{% url 'accounts:password_reset' %}">Forgot Password</a>
      </div>
    </div>
  </form>
  <p class="text-center">
    Not a member?
    <a href="{% url 'accounts:signup' %}">Sign Up</a>
  </p>
</div>
{% endblock content %}

templates/accounts/signup.html
{% extends 'base_accounts.html' %}


{% block content %}
<div class="login-wrap p-4 p-md-5">
                <div class="d-flex">
                  <div class="w-100">
                    <h3 class="mb-4">sign up</h3>
                  </div>
                </div>
                <form action="{% url 'accounts:signup' %}" class="signin-form" method="post">
                    {% csrf_token %}
                    {{ block.super }}
                  <div class="form-group mt-3">
                    <input type="text" name="email" class="form-control" required />
                    <label class="form-control-placeholder" for="email"
                      >Email</label
                    >
                  </div>
                  <div class="form-group mt-3">
                    <input type="text" name="username" class="form-control" required />
                    <label class="form-control-placeholder" for="username"
                      >username</label
                    >
                  </div>
                  <div class="form-group">
                    <input
                      id="password-field"
                      type="password"
                      class="form-control"
                      name="password1"
                      required
                    />
                    <label class="form-control-placeholder" for="password1"
                      >Password</label
                    >
                    <span
                      toggle="#password-field"
                      class="fa fa-fw fa-eye field-icon toggle-password"
                    ></span>
                  </div>
                  <div class="form-group">
                    <input
                      id="password-field"
                      type="password"
                      class="form-control"
                      name="password2"
                      required
                    />
                    <label class="form-control-placeholder" for="password2"
                      >Password Confirmation</label
                    >
                    <span
                      toggle="#password-field"
                      class="fa fa-fw fa-eye field-icon toggle-password"
                    ></span>
                  </div>
                  <div class="form-group">
                    <button
                      type="submit"
                      class="form-control btn btn-primary rounded submit px-3"
                    >
                      sign up
                    </button>
                  </div>
                </form>
                <p class="text-center">
                  Are you a member? <a href="{% url 'accounts:login' %}">Sign In</a>
                </p>
              </div>
{% endblock content %}            