blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestEntriesFeed

app_name = 'blog'

urlpatterns = [
    path('', views.blog_list_view, name='list_view'),
    path('category/<str:cat_name>/', views.blog_list_view, name='category'),
    path('tag/<str:tag_name>/', views.blog_list_view, name='tag'),
    path('search/', views.blog_search_view, name='search'),
    path('<int:pk>/', views.blog_detail_view, name='detail_view'),
    path("rss/feed/", LatestEntriesFeed()),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap

import debug_toolbar

from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap

sitemaps = {
    "static": StaticViewSitemap,
    "blog": BlogSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),

    # app urls
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),


    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path('robots.txt', include('robots.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
    path('tinymce/', include('tinymce.urls')),
    path('captcha/', include('captcha.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from . import views

app_name = 'website'

urlpatterns = [
    path('', views.index_view, name='index'),    
    path('about', views.about_view, name='about'),    
    path('contact', views.contact_view, name='contact'),    
    path('newsletter', views.newsletter_view, name='newsletter'),
]

blog/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from taggit.managers import TaggableManager
from tinymce.models import HTMLField


class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.name


class Post(models.Model):
    image = models.ImageField(upload_to='blog/', default='blog/default_image.png')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='posts', on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=255)
    content = HTMLField()
    tags = TaggableManager()
    category = models.ManyToManyField(Category)
    counted_view = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    login_require = models.BooleanField(default=False)
    published_datetime = models.DateTimeField(null=True)
    created_datetime = models.DateTimeField(auto_now_add=True)
    modified_datetime = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_datetime']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail_view', kwargs={'pk': self.pk})


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    approved = models.BooleanField(default=False)
    created_datetime = models.DateTimeField(auto_now_add=True)
    modified_datetime = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject

blog/forms.py
from django import forms
from .models import Comment
from captcha.fields import CaptchaField


class CommentForm(forms.ModelForm):
    captcha = CaptchaField()

    class Meta:
        model = Comment
        fields = ['post', 'name', 'email', 'subject', 'message']

blog/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.timezone import now
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib import messages

from .forms import CommentForm
from .models import Post, Comment


def blog_list_view(request, **kwargs):
    posts = Post.objects.filter(status=True)
    posts = posts.filter(published_datetime__lte=now()).select_related('author').prefetch_related('category')

    # Filter posts by category
    if kwargs.get("cat_name"):
        posts = posts.filter(category__name=kwargs.get("cat_name"))

    if kwargs.get("tag_name"):
        posts = posts.filter(tags__name__in=[kwargs.get("tag_name")])

    # Paginate posts
    posts = Paginator(posts, 3)
    try:
        page_number = request.GET.get("page")
        posts = posts.get_page(page_number)
    except PageNotAnInteger:
        posts = posts.get_page(1)
    except EmptyPage:
        posts = posts.get_page(1)

    context = {"posts": posts}
    return render(request, "blog/blog-home.html", context)


def blog_detail_view(request, pk):
        queryset = Post.objects.filter(status=True, published_datetime__lte=now())

        post = get_object_or_404(queryset, id=pk)
        post.counted_view += 1
        post.save()

        next_post = queryset.filter(id__gt=post.id).order_by("id").first()
        previous_post = queryset.filter(id__lt=post.id).order_by("id").last()

        comments = Comment.objects.filter(post=post.id, approved=True).order_by('-created_datetime')

        if request.method == "POST":
            form = CommentForm(request.POST)
            if form.is_valid():
                form.save()
                messages.success(request, "your comment has been sent successfully")
            else:
                messages.error(request, "your comment has not been sent")

        form = CommentForm()


        context = {"post": post,
                "next_post": next_post,
                "previous_post": previous_post,
                "comments": comments,
                "form": form}
        
        # if post.login_require is True and user is authenticated
        # show the post
        
        # and if user is not authenticated and post.login_require is True
        # don't show the post
        
        if post.login_require == True and request.user.is_authenticated or post.login_require == False:
            return render(request, "blog/blog-single.html", context)
        else:
            return redirect("accounts:login")

def blog_search_view(request):
    posts = Post.objects.filter(status=True, published_datetime__lte=now())
    if request.method == "GET":
        if s := request.GET.get("q"):
            posts = posts.filter(content__contains=s)

    context = {"posts": posts}
    return render(request, "blog/blog-home.html", context)

templates/blog/blog-ads.html
{% load static %}

<div class="single-sidebar-widget ads-widget">
    <a href="#"
      ><img
        class="img-fluid"
        src="{% static 'img/blog/ads-banner.jpg' %}"
        alt=""
    /></a>
  </div>

templates/blog/blog-category.html
<div class="single-sidebar-widget post-category-widget">
    <h4 class="category-title">Post Catgories</h4>
    <ul class="cat-list">
      {% for name, count in categories.items %}
      <li>
        <a href="{% url 'blog:category' cat_name=name %}" class="d-flex justify-content-between">
          <p>{{ name }}</p>
          <p>{{ count }}</p>
        </a>
      </li>
      {% endfor %}
  </div>

templates/blog/blog-home.html
{% extends '_base.html'%} 
{% load static %} 
{% load blog_tags %} 
{% block title %} blog home {% endblock title %} 
{% block content %}
<!-- start banner Area -->
<section class="banner-area relative blog-home-banner" id="home">
  <div class="overlay overlay-bg"></div>
  <div class="container">
    <div class="row d-flex align-items-center justify-content-center">
      <div class="about-content blog-header-content col-lg-12">
        <h1 class="text-white">Dude You’re Getting a Telescope</h1>
        <p class="text-white">
          There is a moment in the life of any aspiring astronomer that it is
          time to buy that first
        </p>
      </div>
    </div>
  </div>
</section>
<!-- End banner Area -->

<!-- Start top-category-widget Area -->
<section class="top-category-widget-area pt-90 pb-90">
  <div class="container">
    <div class="row">
      <div class="col-lg-4">
        <div class="single-cat-widget">
          <div class="content relative">
            <div class="overlay overlay-bg"></div>
            <a href="#" target="_blank">
              <div class="thumb">
                <img
                  class="content-image img-fluid d-block mx-auto"
                  src="{% static 'img/blog/cat-widget1.jpg' %}"
                  alt=""
                />
              </div>
              <div class="content-details">
                <h4 class="content-title mx-auto text-uppercase">
                  Social life
                </h4>
                <span></span>
                <p>Enjoy your social life together</p>
              </div>
            </a>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="single-cat-widget">
          <div class="content relative">
            <div class="overlay overlay-bg"></div>
            <a href="#" target="_blank">
              <div class="thumb">
                <img
                  class="content-image img-fluid d-block mx-auto"
                  src="{% static 'img/blog/cat-widget2.jpg' %}"
                  alt=""
                />
              </div>
              <div class="content-details">
                <h4 class="content-title mx-auto text-uppercase">Politics</h4>
                <span></span>
                <p>Be a part of politics</p>
              </div>
            </a>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="single-cat-widget">
          <div class="content relative">
            <div class="overlay overlay-bg"></div>
            <a href="#" target="_blank">
              <div class="thumb">
                <img
                  class="content-image img-fluid d-block mx-auto"
                  src="{% static 'img/blog/cat-widget3.jpg' %}"
                  alt=""
                />
              </div>
              <div class="content-details">
                <h4 class="content-title mx-auto text-uppercase">Food</h4>
                <span></span>
                <p>Let the food be finished</p>
              </div>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- End top-category-widget Area -->

<!-- Start post-content Area -->
<section class="post-content-area">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 posts-list">
        {% for post in posts %}
        <div class="single-post row">
          <div class="col-lg-3 col-md-3 meta-details">
            <ul class="tags">
              <li>
                  {% for cat in post.category.all %}
                   <a href="{% url 'blog:category' cat_name=cat.name %}"> {{ cat.name }} {% if not forloop.last %} , {% endif %} </a>
                  {% endfor %}
                </li>
            </ul>
            <div class="user-details row">
              <p class="user-name col-lg-12 col-md-12 col-6">
                <a href="#">{{ post.author.username }}</a>
                <span class="lnr lnr-user"></span>
              </p>
              <p class="date col-lg-12 col-md-12 col-6">
                <a href="#">{{post.published_datetime|date:"d M Y" }}</a>
                <span class="lnr lnr-calendar-full"></span>
              </p>
              <p class="view col-lg-12 col-md-12 col-6">
                <a href="#">{{post.counted_view}} Views</a>
                <span class="lnr lnr-eye"></span>
              </p>
              <p class="comments col-lg-12 col-md-12 col-6">
                <a href="#">{% comment_count pid=post.id %} Comments</a> <span class="lnr lnr-bubble"></span>
              </p>
            </div>
          </div>
          <div class="col-lg-9 col-md-9">
            <div class="feature-img">
              <img
                class="img-fluid"
                src="{{ post.image.url }}"
                alt=""
              />
            </div>
            <a
              class="posts-title"
              href="{% url 'blog:detail_view' pk=post.id %}"
              ><h3>{{post.title}}</h3></a
            >
            <p class="excert">
              {{ post.content|safe|truncatewords:1  }}
            </p>
            <a
              href="{% url 'blog:detail_view' pk=post.id %}"
              class="primary-btn"
              >View More</a
            >
          </div>
        </div>
        {% endfor %}

        <nav class="blog-pagination justify-content-center d-flex">
          <ul class="pagination">
            {% if posts.has_previous %}
            <li class="page-item">
              <a href="?page={{ posts.previous_page_number }}" class="page-link" aria-label="Previous">
                <span aria-hidden="true">
                  <span class="lnr lnr-chevron-left"></span>
                </span>
              </a>
            </li>
            {% endif %}

            {% for i in posts.paginator.page_range %}
            {% if posts.number == i %}
            <li class="page-item active">
              <a href="?page={{ i }}" class="page-link">{{ i }}</a>
            </li>
            {% else %}
            <li class="page-item">
              <a href="?page={{ i }}" class="page-link">{{ i }}</a>
            </li>
            {% endif %}
            {% endfor %}

            {% if posts.has_next %}
            <li class="page-item">
              <a href="?page={{ posts.next_page_number }}" class="page-link" aria-label="Next">
                <span aria-hidden="true">
                  <span class="lnr lnr-chevron-right"></span>
                </span>
              </a>
            </li>
            {% endif %}
          </ul>
        </nav>
      </div>
      <div class="col-lg-4 sidebar-widgets">
        <div class="widget-wrap">
          {% include 'blog/blog-search.html' %}
          {% include 'blog/blog-writer.html' %}
          {% latestposts %}
          {% post_categories %}

        </div>
      </div>
    </div>
  </div>
</section>
<!-- End post-content Area -->
{% endblock content %}

templates/blog/blog-latest-post.html
{% load static %}
{% load humanize %}

<div class="single-sidebar-widget popular-post-widget">
    <h4 class="popular-title">Latest Posts</h4>
    <div class="popular-post-list">
      {% for post in posts %}
      <div class="single-post-list d-flex flex-row align-items-center">
        <div class="thumb">
          <img
            class="img-fluid"
            src="{{ post.image.url }}"
            alt=""
          />
        </div>
        <div class="details">
          <a href="{% url 'blog:detail_view' post.id %}" 
            ><h6>{{ post.title }}</h6></a
          >
          <p>{{ post.published_datetime|naturaltime }}</p>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>

templates/blog/blog-search.html
<div class="single-sidebar-widget search-widget">
    <form class="search-form" action="{% url 'blog:search' %}" method="get">
      <input
        placeholder="Search Posts"
        name="q"
        type="text"
        onfocus="this.placeholder = ''"
        onblur="this.placeholder = 'Search Posts'"
      />
      <button type="submit"><i class="fa fa-search"></i></button>
    </form>
  </div>

templates/blog/blog-single.html
{% extends '_base.html' %}
{% load static %}
{% load blog_tags %}

{% block title %} blog detail {% endblock title %}

{% block content %}
    <!-- start banner Area -->
    <section class="relative about-banner">
        <div class="overlay overlay-bg"></div>
        <div class="container">
            <div class="row d-flex align-items-center justify-content-center">
                <div class="about-content col-lg-12">
                    <h1 class="text-white">
                        {{ post.title }}
                    </h1>
                    <p class="text-white link-nav"><a href="{% url 'website:index' %}">Home </a> <span
                            class="lnr lnr-arrow-right"></span><a href="{% url 'blog:list_view' %}">Blog </a> <span
                            class="lnr lnr-arrow-right"></span> {{ post.title }} </p>
                </div>
            </div>
        </div>
    </section>
    <!-- End banner Area -->

    <!-- Start post-content Area -->
    <section class="post-content-area single-post-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 posts-list">
                    <div class="single-post row">
                        <div class="col-lg-12">
                            <div class="feature-img">
                                <img class="img-fluid" src="{{ post.image.url }}" alt="">
                            </div>
                        </div>
                        <div class="col-lg-3  col-md-3 meta-details">
                            <ul class="tags">
                                <li><a href="#">
                                    {% for cat in post.category.all %}
                                        <a> {{ cat.name }} {% if not forloop.last %} , {% endif %} </a>
                                    {% endfor %}</a>
                                </li>
                            </ul>
                            <div class="user-details row">
                                <p class="user-name col-lg-12 col-md-12 col-6"><a
                                        href="#">{{ post.author.username }}</a> <span class="lnr lnr-user"></span>
                                </p>
                                <p class="date col-lg-12 col-md-12 col-6"><a
                                        href="#">{{ post.published_datetime|date:"d M Y" }}</a> <span
                                        class="lnr lnr-calendar-full"></span></p>
                                <p class="view col-lg-12 col-md-12 col-6"><a href="#">{{ post.counted_view }} Views</a>
                                    <span class="lnr lnr-eye"></span></p>
                                <p class="comments col-lg-12 col-md-12 col-6"><a href="#">{{ comments|length }} Comments</a> <span
                                        class="lnr lnr-bubble"></span></p>
                            </div>
                        </div>
                        <div class="col-lg-9 col-md-9">
                            <h3 class="mt-20 mb-20">{{ post.title }}</h3>
                            <p class="excert">
                                {{ post.content|safe }}
                            </p>
                        </div>
                        <div class="col-lg-12">
                            <div class="row mt-30 mb-30">
                                <div class="col-lg-12 mt-30">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="navigation-area">
                        <div class="row">

                            <div class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
                                {% if previous_post %}
                                    <div class="thumb">
                                        <a href="{% url 'blog:detail_view' previous_post.id %}"><img class="img-fluid"
                                                                                                     src="{{ previous_post.image.url }}"
                                                                                                     alt=""></a>
                                    </div>
                                    <div class="arrow">
                                        <a href="{% url 'blog:detail_view' previous_post.id %}"><span
                                                class="lnr text-white lnr-arrow-left"></span></a>
                                    </div>
                                    <div class="detials">
                                        <p>Prev Post</p>
                                        <a href="{% url 'blog:detail_view' previous_post.id %}">
                                            <h4>{{ previous_post }}</h4></a>
                                    </div>
                                {% endif %}
                            </div>


                            <div class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
                                {% if next_post %}
                                    <div class="detials">
                                        <p>Next Post</p>
                                        <a href="{% url 'blog:detail_view' next_post.id %}"><h4>{{ next_post }}</h4></a>
                                    </div>
                                    <div class="arrow">
                                        <a href="{% url 'blog:detail_view' next_post.id %}"><span
                                                class="lnr text-white lnr-arrow-right"></span></a>
                                    </div>
                                    <div class="thumb">
                                        <a href="{% url 'blog:detail_view' next_post.id %}"><img class="img-fluid"
                                                                                                 src="{{ next_post.image.url }}"
                                                                                                 alt=""></a>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>


                    <div class="comments-area">
                        <h4>{{ comments|length }} Comments</h4>
                        {% for comment in comments %}
                            <div class="comment-list">
                                <div class="single-comment justify-content-between d-flex">
                                    <div class="user justify-content-between d-flex">
                                        <div class="thumb">
                                            <img src="{% static 'img/blog/default-avatar.jpg' %}" style="max-width: 70px;" alt="">
                                        </div>
                                        <div class="desc">
                                            <h5><a href="#">{{ comment.name }}</a></h5>
                                            <p class="date">{{ comment.created_datetime|date:"d M Y" }} </p>
                                            <p class="comment">
                                                {{ comment.message }}
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% empty %}
                            <p> there is no any comment, be the first one tell the thoughts about post! </p>
                        {% endfor %}
                    </div>
                    <div class="comment-form">
                        <h4>Leave a Comment</h4>
                        <form method="post" action="{% url 'blog:detail_view' pk=post.id %}">
                            {% csrf_token %}
                            <input type="hidden" name="post" value="{{ post.id }}">
                            {% if request.user.is_authenticated %}
                            <input type="hidden" name="name" value="{{ request.user.username }}">
                            <input type="hidden" name="email" value="{{ request.user.email }}">
                            {% else %}
                            <div class="form-group form-inline">
                                <div class="form-group col-lg-6 col-md-12 name">
                                    <input type="text" class="form-control" name="name" placeholder="Enter Name"
                                           onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Name'">
                                </div>
                                <div class="form-group col-lg-6 col-md-12 email">
                                    <input type="email" class="form-control" name="email"
                                           placeholder="Enter email address" onfocus="this.placeholder = ''"
                                           onblur="this.placeholder = 'Enter email address'">
                                </div>
                            </div>
                            {% endif %}
                            <div class="form-group">
                                <input type="text" class="form-control" name="subject" placeholder="Subject"
                                       onfocus="this.placeholder = ''" onblur="this.placeholder = 'Subject'">
                            </div>
                            <div class="form-group">
                                <textarea class="form-control mb-10" rows="5" name="message" placeholder="Messege"
                                          onfocus="this.placeholder = ''" onblur="this.placeholder = 'Messege'"
                                          required=""></textarea>
                            </div>
                            <button type="submit" class="primary-btn text-uppercase">Post Comment</button>
                            <div class="pt-20 align-middle">
                                <div>

                                    {{ form.captcha }}
                                </div>
                            </div>
                        </form>
                    </div>

                </div>
                <div class="col-lg-4 sidebar-widgets">
                    <div class="widget-wrap">
                        {% include 'blog/blog-search.html' %}
                        {% include 'blog/blog-writer.html' %}
                        {% include 'blog/blog-tag.html' %}
                        {% latestposts %}
                        {% post_categories %}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End post-content Area -->

{% endblock content %}

templates/blog/blog-tag.html
<div class="single-sidebar-widget tag-cloud-widget">
    <h4 class="tagcloud-title">Tag Clouds</h4>
    <ul>
        {% for tag in post.tags.all %}
            <li><a href="{% url 'blog:tag' tag_name=tag.name %}"> {{ tag.name }} </a></li>
        {% endfor %}
    </ul>
</div>

templates/blog/blog-writer.html
{% load static %}

<div class="single-sidebar-widget user-info-widget">
    <img src="{% static 'img/blog/profile.jpg' %}" alt="" style="max-width: 200px; max-height: 200px; border-radius: 100px;" />
    <a href="#"><h4>Ali Mohammadinezhad</h4></a>
    <p>Senior blog writer</p>
    <p>
      Boot camps have its supporters andit sdetractors. Some people do
      not understand why you should have to spend money on boot camp
      when you can get. Boot camps have itssuppor ters andits
      detractors.
    </p>
  </div>