accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = "accounts"

urlpatterns = [
    
    path("logout/", views.logout_view, name="logout"),
    path("signup/", views.signup_view, name="signup"),
    path("login/", views.login_view, name="login"),
    
    # reset password django.contrib.auth
    path(
        "password_reset/",
        views.CustomPasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.CustomPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.CustomPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestEntriesFeed

app_name = 'blog'

urlpatterns = [
    path('', views.blog_list_view, name='list_view'),
    path('category/<str:cat_name>/', views.blog_list_view, name='category'),
    path('tag/<str:tag_name>/', views.blog_list_view, name='tag'),
    path('search/', views.blog_search_view, name='search'),
    path('<int:pk>/', views.blog_detail_view, name='detail_view'),
    path("rss/feed/", LatestEntriesFeed()),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap

import debug_toolbar

from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap

sitemaps = {
    "static": StaticViewSitemap,
    "blog": BlogSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),

    # app urls
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),


    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path('robots.txt', include('robots.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
    path('tinymce/', include('tinymce.urls')),
    path('captcha/', include('captcha.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from . import views

app_name = 'website'

urlpatterns = [
    path('', views.index_view, name='index'),    
    path('about', views.about_view, name='about'),    
    path('contact', views.contact_view, name='contact'),    
    path('newsletter', views.newsletter_view, name='newsletter'),
]

templates/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="zxx" class="no-js">
<head>
    <!-- Mobile Specific Meta -->
    <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static 'img/fav.png' %}"/>
    <!-- Author Meta -->
    <meta name="author" content="colorlib"/>
    <!-- Meta Description -->
    <meta name="description" content=""/>
    <!-- Meta Keyword -->
    <meta name="keywords" content=""/>
    <!-- meta character set -->
    <meta charset="UTF-8"/>
    <!-- Site Title -->


    <title>{% block title %}Travel{% endblock title %}</title>


    <link
            href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700"
            rel="stylesheet"
    />
    <!--
        CSS
        ============================================= -->
    <link rel="stylesheet" href="{% static 'css/linearicons.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/main.css' %}"/>
</head>
<body>
<header id="header">

{% for message in messages %}
                        <div class="container-fluid p-0" style="max-width: 90%;">
                            <div class="alert {{ message.tags }} alert-dismissible" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">×</span>
                                </button>
                                {{ message }}
                            </div>
                        </div>
                    {% endfor %}
    <div class="header-top">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-6 col-sm-6 col-6 header-top-left">
                    <ul>
                        {% if request.user.is_authenticated %}
                        <li><a href="#">Logged in as {{ request.user.username }}</a></li>
                        <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                        {% else %}
                        <li><a href="{% url 'accounts:login' %}">Login</a></li>
                        <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="container main-menu">
        <div class="row align-items-center justify-content-between d-flex">
            <div id="logo">
                <a href="{% url 'website:index' %}"
                ><img src="{% static 'img/logo.png' %}" alt="" title=""
                /></a>
            </div>
            <nav id="nav-menu-container">
                <ul class="nav-menu">
                    <li><a href="{% url "website:index" %}">Home</a></li>
                    <li><a href="{% url "website:about" %}">About</a></li>
                    <li>
                        <a href="{% url "blog:list_view" %}">Blog</a>
                    </li>
                    <li><a href="{% url "website:contact" %}">Contact</a></li>
                </ul>
            </nav>
            <!-- #nav-menu-container -->
            
        </div>
        
    </div>
</header>
<!-- #header -->

{% block content %}{% endblock content %}

<script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
<script src="{% static 'js/jquery-ui.js' %}"></script>
<script src="{% static 'js/easing.min.js' %}"></script>
<script src="{% static 'js/hoverIntent.js' %}"></script>
<script src="{% static 'js/superfish.min.js' %}"></script>
<script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/mail-script.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>


<!-- start footer Area -->
<footer class="footer-area section-gap">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6>About Agency</h6>
                    <p>
                        The world has become so fast paced that people don’t want to
                        stand by reading a page of information, they would much rather
                        look at a presentation and understand the message. It has come
                        to a point
                    </p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6>Navigation Links</h6>
                    <div class="row">
                        <div class="col">
                            <ul>
                                <li><a href="{% url 'website:index' %}">Home</a></li>
                                <li><a href="{% url 'blog:list_view' %}">Blog</a></li>
                                <li><a href="{% url 'website:contact' %}">Contact</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <h6>Newsletter</h6>
                    <p>
                        For business professionals caught between high OEM price and
                        mediocre print and graphic output.
                    </p>
                    <div>
                        <form
                                action="{% url 'website:newsletter' %}"
                                method="post"
                                class="subscription relative"
                        >
                            {% csrf_token %}
                            <div class="input-group d-flex flex-row">
                                <input
                                        name="email"
                                        placeholder="Email Address"
                                        onfocus="this.placeholder = ''"
                                        onblur="this.placeholder = 'Email Address '"
                                        required=""
                                        type="email"
                                />
                                <button class="btn bb-btn" type="submit">
                                    <span class="lnr lnr-location"></span>
                                </button>
                            </div>
                            <div class="mt-10 info"></div>
                        </form>
 
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="single-footer-widget mail-chimp">
                    <h6 class="mb-20">InstaFeed</h6>
                    <ul class="instafeed d-flex flex-wrap">
                        <li><img src="{% static 'img/i1.jpg' %}" alt=""/></li>
                        <li><img src="{% static 'img/i2.jpg' %}" alt=""/></li>
                        <li><img src="{% static 'img/i3.jpg' %}" alt=""/></li>
                        <li><img src="{% static 'img/i4.jpg' %}" alt=""/></li>
                        <li><img src="{% static 'img/i5.jpg' %}" alt=""/></li>
                        <li><img src="{% static 'img/i6.jpg' %}" alt=""/></li>
                        <li><img src="{% static 'img/i7.jpg' %}" alt=""/></li>
                        <li><img src="{% static 'img/i8.jpg' %}" alt=""/></li>
                    </ul>
                </div>
            </div>
        </div>


        <div
                class="row footer-bottom d-flex justify-content-between align-items-center"
        >
        </div>
    </div>
</footer>
<!-- End footer Area -->
</body>
</html>

templates/base_accounts.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Login</title>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>
  <body>
    {% for message in messages %}
    <div class="container-fluid p-0" style="max-width: 90%">
      <div class="alert {{ message.tags }} alert-dismissible" role="alert">
        <button
          type="button"
          class="close"
          data-dismiss="alert"
          aria-label="Close"
        >
          <span aria-hidden="true">×</span>
        </button>
        {{ message }}
      </div>
    </div>
    {% endfor %}
    <section class="ftco-section">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-md-6 text-center mb-5"></div>
        </div>
        <div class="row justify-content-center">
          <div class="col-md-7 col-lg-5">
            <div class="wrap">
              <div
                class="img"
                style="background-image: url({% static 'img/bg-1.jpg' %})"
              ></div>
              {% block content %}

              {% if form.errors %}
              {% for field in form %}
        
                   {% for error in field.errors %}
                   <div class="alert alert-danger">
                     {{field.label}}: <p>
                      {{ error|escape }}
                     </p> 

                   </div>
                   {% endfor %}
        
              {% endfor %}
                {% endif %}
                {% endblock content %}
            
              </div>
          </div>
        </div>
      </div>
    </section>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>